const API_URL='https://script.google.com/macros/s/AKfycbyFr62Z-zPn0exJEYKkROFAjBpRNuATHO62scf-H8grDaOi8om4TXt2e0dK-rC7cAbR/exec';const CACHE_KEY='madrasah_cache_v1';async function apiRequest(action,data={}){try{const r=await fetch(API_URL+'?action='+encodeURIComponent(action),{cache:'no-store'});if(!r.ok)throw Error(r.status);return await r.json()}catch(e){return{success:false,error:String(e)}}}async function fetchAllData(){const r=await apiRequest('all');if(r.success){localStorage.setItem(CACHE_KEY,JSON.stringify(r));return r}const c=localStorage.getItem(CACHE_KEY);return c?JSON.parse(c):demoData()}function demoData(){return DEFAULT_DATA}
const DEFAULT_DATA={success:true,version:'default-20260924',updatedAt:'2026-09-24T00:00:00Z',data:{
settings:{name:'আল-হুদা মডেল মাদ্রাসা',arabicName:'مدرسة الهدى النموذجية',motto:'ইলম, আমল ও আখলাক',founded:'২০২৪',principal:'মাওলানা আব্দুল্লাহ',phone:'০১৭০০-০০০০০০',email:'info@madrasah.example',address:'স্টেশন পাড়া, বাংলাদেশ',description:'ইসলামি মূল্যবোধ, আধুনিক শিক্ষা ও মানবিকতার সমন্বিত শিক্ষাঙ্গন।'},
notices:[{id:'N001',title:'২০২৬ শিক্ষাবর্ষে ভর্তি কার্যক্রম শুরু',date:'২৪ সেপ্টেম্বর ২০২৬',category:'ভর্তি',important:true,status:'Published'},{id:'N002',title:'অর্ধবার্ষিক পরীক্ষার প্রস্তুতি সংক্রান্ত নোটিশ',date:'২০ সেপ্টেম্বর ২০২৬',category:'পরীক্ষা',important:false,status:'Published'},{id:'N003',title:'সাপ্তাহিক ছুটির দিনের সময়সূচি',date:'১৮ সেপ্টেম্বর ২০২৬',category:'সাধারণ',important:false,status:'Published'}],
teachers:[{id:'T001',name:'মাওলানা আব্দুল্লাহ',designation:'অধ্যক্ষ',department:'প্রশাসন',subject:'ইসলামিয়াত',education:'কামিল',experience:'১৫ বছর',status:'Active'},{id:'T002',name:'মুফতি আব্দুর রহমান',designation:'সহকারী অধ্যাপক',department:'দ্বীনি শিক্ষা',subject:'ফিকহ',education:'দাওরায়ে হাদিস',experience:'১০ বছর',status:'Active'},{id:'T003',name:'মোঃ হাসান আলী',designation:'প্রভাষক',department:'সাধারণ শিক্ষা',subject:'গণিত',education:'এমএসসি',experience:'৮ বছর',status:'Active'}],
students:[{id:'ST001',name:'আহমাদুল্লাহ',roll:'101',class:'ষষ্ঠ',department:'সাধারণ',session:'2026',status:'Active'},{id:'ST002',name:'মুহাম্মাদ আবির',roll:'102',class:'সপ্তম',department:'হিফজ',session:'2026',status:'Active'},{id:'ST003',name:'মোঃ সাইফুল ইসলাম',roll:'103',class:'অষ্টম',department:'সাধারণ',session:'2026',status:'Active'}],
courses:[{id:'C001',title:'হিফজুল কুরআন',description:'পূর্ণাঙ্গ কুরআন হিফজ ও তাজবিদ শিক্ষা',department:'হিফজ',status:'Active'},{id:'C002',title:'কিতাব বিভাগ',description:'কুরআন, হাদিস, ফিকহ ও আরবি ভাষা শিক্ষা',department:'দ্বীনি শিক্ষা',status:'Active'},{id:'C003',title:'সাধারণ শিক্ষা',description:'বাংলা, ইংরেজি, গণিত, বিজ্ঞান ও আইসিটি',department:'সাধারণ',status:'Active'}],
departments:[{id:'D001',name:'হিফজ বিভাগ',description:'কুরআন হিফজ ও তাজবিদ'},{id:'D002',name:'দ্বীনি শিক্ষা বিভাগ',description:'কিতাব, হাদিস ও ফিকহ'},{id:'D003',name:'সাধারণ শিক্ষা বিভাগ',description:'আধুনিক সাধারণ শিক্ষা'}],
news:[{id:'NW001',title:'নতুন একাডেমিক ভবন উদ্বোধন',author:'মাদ্রাসা কর্তৃপক্ষ',date:'২০ সেপ্টেম্বর ২০২৬',short:'নতুন ভবনে আধুনিক শ্রেণিকক্ষ ও পাঠাগার সুবিধা যুক্ত হয়েছে।',status:'Published'},{id:'NW002',title:'বার্ষিক ক্রীড়া প্রতিযোগিতা অনুষ্ঠিত',author:'মাদ্রাসা কর্তৃপক্ষ',date:'১২ সেপ্টেম্বর ২০২৬',short:'শিক্ষার্থীদের অংশগ্রহণে প্রাণবন্ত ক্রীড়া আয়োজন।',status:'Published'}],
events:[{id:'E001',title:'সীরাতুন্নবী আলোচনা সভা',date:'০৫ অক্টোবর ২০২৬',location:'মাদ্রাসা অডিটোরিয়াম',details:'শিক্ষক-শিক্ষার্থীদের অংশগ্রহণে আলোচনা সভা।'},{id:'E002',title:'অভিভাবক সমাবেশ',date:'১২ অক্টোবর ২০২৬',location:'মাদ্রাসা প্রাঙ্গণ',details:'শিক্ষার্থীদের অগ্রগতি নিয়ে মতবিনিময়।'}],
gallery:[{id:'G001',title:'মাদ্রাসা ক্যাম্পাস',category:'Campus',image:'https://images.unsplash.com/photo-1609599006353-e629aaabfeae?auto=format&fit=crop&w=900&q=80'},{id:'G002',title:'শিক্ষার্থীদের পাঠদান',category:'Classroom',image:'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=900&q=80'},{id:'G003',title:'ইসলামিক অনুষ্ঠান',category:'Islamic Program',image:'https://images.unsplash.com/photo-1542816417-0983c9c9ad53?auto=format&fit=crop&w=900&q=80'}],
faq:[{id:'F001',question:'ভর্তি কীভাবে করা যাবে?',answer:'অনলাইন ভর্তি ফর্ম পূরণ করে আবেদন করতে পারবেন।'},{id:'F002',question:'মাদ্রাসায় কোন কোন বিভাগ আছে?',answer:'হিফজ, দ্বীনি শিক্ষা ও সাধারণ শিক্ষা বিভাগ রয়েছে।'}],
articles:[{id:'A001',title:'সন্তানের নৈতিক শিক্ষায় পরিবারের ভূমিকা',author:'মাদ্রাসা প্রকাশনা বিভাগ',short:'নৈতিক শিক্ষা পরিবার থেকেই শুরু হয়।',details:'সন্তানের চরিত্র গঠনে পরিবার, শিক্ষক ও সমাজের সমন্বিত ভূমিকা প্রয়োজন।',category:'ইসলামিক',date:'১৫ সেপ্টেম্বর ২০২৬',status:'Published'}],
results:[{id:'R001',studentId:'ST001',roll:'101',name:'আহমাদুল্লাহ',class:'ষষ্ঠ',exam:'অর্ধবার্ষিক',subject:'বাংলা',marks:'৮৫',gpa:'5.00',grade:'A+',result:'Passed'},{id:'R002',studentId:'ST001',roll:'101',name:'আহমাদুল্লাহ',class:'ষষ্ঠ',exam:'অর্ধবার্ষিক',subject:'গণিত',marks:'৯০',gpa:'5.00',grade:'A+',result:'Passed'}],
videos:[{id:'V001',title:'মাদ্রাসা পরিচিতি',youtube:'https://www.youtube.com/watch?v=dQw4w9WgXcQ',category:'Introduction',description:'মাদ্রাসার সংক্ষিপ্ত পরিচিতি'}]
}};