const SPREADSHEET_ID='1aQXnM2PeR82t1jm7LUyw3wEu_PeiCL2irbttl0n-4Ck';
const SHEETS={Settings:['key','value'],Notices:['id','title','date','category','url','important','status'],News:['id','title','author','date','short','details','status'],Events:['id','title','date','location','details'],Teachers:['id','name','photo','designation','department','subject','education','experience','mobile','email','joiningDate','status','bio'],Staff:['id','name','designation','department','mobile','status'],Students:['id','name','photo','roll','registration','class','department','session','gender','guardian','mobile','status'],Courses:['id','title','description','department','class','fee','status'],Departments:['id','name','description','status'],Results:['id','studentId','roll','name','class','exam','subject','marks','gpa','grade','result'],Routine:['id','type','class','day','time','subject','teacher'],Gallery:['id','image','title','category','date','description'],Videos:['id','title','youtube','thumbnail','category','description'],Articles:['id','title','author','thumbnail','short','details','category','tags','date','status'],FAQ:['id','question','answer','status'],Admission:['id','name','father','mother','dob','gender','previous','result','class','department','mobile','guardianMobile','address','photo','documents','status','createdAt'],Contact:['id','name','mobile','email','subject','message','createdAt','status'],Donations:['id','method','accountName','accountNumber','qr','details','status'],Messages:['id','name','mobile','email','subject','message','createdAt','status'],Users:['id','username','passwordHash','role','status'],Admin:['id','username','passwordHash','role','status'],Logs:['date','time','admin','action','module','recordId','status']};
function doGet(e){try{const a=e&&e.parameter&&e.parameter.action||'all';if(a==='all')return json({success:true,version:version(),updatedAt:new Date().toISOString(),data:getAllData()});if(a==='getSheets')return json({success:true,data:getSheets()});if(a==='setupSheets')return json({success:true,data:setupSheets()});if(a==='backupData')return json({success:true,data:backupData()});if(a==='syncData')return json({success:true,data:getAllData()});if(a==='getSettings')return json({success:true,data:getSettings()});const n=a.replace(/^get/,'');if(SHEETS[n])return json({success:true,data:getData(n)});return json({success:false,error:'Unknown action'});}catch(err){return json({success:false,error:String(err)})}}
function doPost(e){try{const b=JSON.parse(e.postData.contents||'{}'),a=b.action||'saveData';if(a==='saveAdmission')return json({success:true,data:saveData('Admission',b.data||b)});if(a==='saveMessage')return json({success:true,data:saveData('Messages',b.data||b)});if(a==='saveSettings')return json({success:true,data:saveData('Settings',b.data||b)});if(a==='saveData')return json({success:true,data:saveData(b.sheet,b.data)});if(a==='updateData')return json({success:true,data:updateData(b.sheet,b.id,b.data)});if(a==='deleteData')return json({success:true,data:deleteData(b.sheet,b.id)});return json({success:false,error:'Unknown action'});}catch(err){return json({success:false,error:String(err)})}}
function json(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON)}
function ss(){return SpreadsheetApp.openById(SPREADSHEET_ID)}
function getSheets(){return ss().getSheets().map(s=>s.getName())}
function setupSheet(name,headers){const s=ss().getSheetByName(name)||ss().insertSheet(name);setupSheetHeader(s,headers);return s.getName()}
function setupSheetHeader(sheet,headers){if(sheet.getLastRow()===0)sheet.appendRow(headers);else sheet.getRange(1,1,1,headers.length).setValues([headers])}
function setupSheets(){Object.keys(SHEETS).forEach(n=>setupSheet(n,SHEETS[n]));return getSheets()}
function getData(name){const s=ss().getSheetByName(name);if(!s||s.getLastRow()<2)return[];const v=s.getDataRange().getValues(),h=v.shift();return v.filter(r=>r.some(Boolean)).map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]])))}
function getAllData(){const o={};Object.keys(SHEETS).forEach(n=>o[n.charAt(0).toLowerCase()+n.slice(1)]=getData(n));return o}
function saveData(name,data){const s=ss().getSheetByName(name)||setupSheet(name,Object.keys(data||{}));const h=s.getRange(1,1,1,s.getLastColumn()).getValues()[0];s.appendRow(h.map(k=>data[k]??''));return data}
function updateData(name,id,data){const s=ss().getSheetByName(name);if(!s)return false;const v=s.getDataRange().getValues(),h=v.shift(),ix=h.indexOf('id');for(let i=0;i<v.length;i++)if(String(v[i][ix])===String(id)){s.getRange(i+2,1,1,h.length).setValues([h.map((k,j)=>data[k]??v[i][j])]);return true}return false}
function deleteData(name,id){const s=ss().getSheetByName(name);if(!s)return false;const v=s.getDataRange().getValues(),h=v.shift(),ix=h.indexOf('id');for(let i=0;i<v.length;i++)if(String(v[i][ix])===String(id)){s.deleteRow(i+2);return true}return false}
function getSettings(){return getData('Settings')}function getNotices(){return getData('Notices')}function getTeachers(){return getData('Teachers')}function getStudents(){return getData('Students')}function getCourses(){return getData('Courses')}function getResults(){return getData('Results')}function getGallery(){return getData('Gallery')}function getEvents(){return getData('Events')}function getNews(){return getData('News')}function getArticles(){return getData('Articles')}function getFAQ(){return getData('FAQ')}
function getSheets(){return ss().getSheets().map(s=>s.getName())}function createHeaders(){return SHEETS}function doGate(){return true}function syncData(){return getAllData()}function pushData(){return true}function backupData(){const n='Backup_'+Utilities.formatDate(new Date(),Session.getScriptTimeZone(),'yyyyMMdd_HHmmss');ss().insertSheet(n).getRange(1,1).setValue(JSON.stringify(getAllData()));return n}function version(){return Utilities.formatDate(new Date(),Session.getScriptTimeZone(),'yyyyMMddHHmmss')}function install(){setupSheets()}